"use client";

export default function TermsAndConditions() {
  return (
    <>
      <style>{`
        body {
          margin: 0;
          font-family: "Segoe UI", sans-serif;
          background: #f8fafc;
          color: #1f2937;
        }

        .termsWrapper {
          width: 100%;
          min-height: 100vh;
          padding: 40px 20px;
          display: flex;
          justify-content: center;
          align-items: flex-start;
        }

        .termsContainer {
          width: 100%;
          max-width: 900px;
          background: #ffffff;
          padding: 40px;
          border-radius: 12px;
          box-shadow: 0 10px 30px rgba(0, 0, 0, 0.05);
        }

        .title {
          font-size: 32px;
          font-weight: 600;
          color: #111827;
          margin-bottom: 10px;
        }

        .subtitle {
          font-size: 14px;
          color: #6b7280;
          margin-bottom: 30px;
        }

        .section {
          margin-top: 30px;
        }

        .section h2 {
          font-size: 20px;
          margin-bottom: 10px;
          color: #111827;
        }

        .section p {
          font-size: 15px;
          color: #374151;
          line-height: 1.6;
        }

        .list {
          margin-top: 10px;
          padding-left: 20px;
        }

        .list li {
          margin-bottom: 8px;
          font-size: 15px;
          color: #374151;
        }

        .highlight {
          background: #fef3c7;
          padding: 12px;
          border-radius: 6px;
          border-left: 4px solid #f59e0b;
          margin-top: 20px;
          font-size: 14px;
        }

        .footer {
          margin-top: 40px;
          padding-top: 20px;
          border-top: 1px solid #e5e7eb;
          font-size: 14px;
          color: #6b7280;
        }

        a {
          color: #2563eb;
          text-decoration: none;
        }

        a:hover {
          text-decoration: underline;
        }

        /* RESPONSIVE */

        @media (max-width: 1200px) {
          .termsContainer {
            max-width: 800px;
          }
        }

        @media (max-width: 992px) {
          .termsContainer {
            padding: 30px;
          }
        }

        @media (max-width: 768px) {
          .title {
            font-size: 26px;
          }

          .section h2 {
            font-size: 18px;
          }

          .termsContainer {
            padding: 25px;
          }
        }

        @media (max-width: 480px) {
          .termsContainer {
            padding: 20px;
          }

          .title {
            font-size: 22px;
          }

          .section p,
          .list li {
            font-size: 14px;
          }
        }
      `}</style>

      <div className="termsWrapper">
        <div className="termsContainer">

          <h1 className="title">Terms & Conditions</h1>
          <p className="subtitle">Effective Date: 2026</p>

          <div className="section">
            <p>
              Welcome to SEO Agent. By accessing or using our platform, you agree
              to comply with and be bound by the following Terms and Conditions.
              Please read them carefully before using the service.
            </p>
          </div>

          <div className="section">
            <h2>1. Use of Service</h2>
            <p>
              SEO Agent provides tools to analyze and optimize WordPress website
              SEO. You agree to use this service only for lawful purposes and in
              compliance with all applicable regulations.
            </p>
          </div>

          <div className="section">
            <h2>2. User Responsibilities</h2>
            <ul className="list">
              <li>You are responsible for maintaining the confidentiality of your credentials.</li>
              <li>You must ensure you have authorization to access connected websites.</li>
              <li>You agree not to misuse or attempt unauthorized system access.</li>
            </ul>
          </div>

          <div className="section">
            <h2>3. Data Handling</h2>
            <p>
              We do not store your WordPress credentials permanently. All data
              interactions are handled securely during active sessions only.
            </p>
            <div className="highlight">
              You are solely responsible for any changes made to your website using this platform.
            </div>
          </div>

          <div className="section">
            <h2>4. SEO Suggestions</h2>
            <p>
              The SEO suggestions generated by our system are based on automated
              analysis and AI models. While we aim for accuracy, we do not guarantee
              improvements in rankings or traffic.
            </p>
          </div>

          <div className="section">
            <h2>5. Plugin Requirement</h2>
            <p>
              Certain features, such as direct SEO updates, require installation of
              the SEO Agent WordPress plugin. Without it, some functionality may be limited.
            </p>
          </div>

          <div className="section">
            <h2>6. Limitation of Liability</h2>
            <p>
              SEO Agent shall not be held liable for any damages, data loss, or issues
              arising from the use of this platform, including incorrect SEO updates or website changes.
            </p>
          </div>

          <div className="section">
            <h2>7. Service Availability</h2>
            <p>
              We reserve the right to modify, suspend, or discontinue any part of
              the service at any time without prior notice.
            </p>
          </div>

          <div className="section">
            <h2>8. Changes to Terms</h2>
            <p>
              These Terms & Conditions may be updated periodically. Continued use
              of the platform constitutes acceptance of those changes.
            </p>
          </div>

          <div className="section">
            <h2>9. Contact</h2>
            <p>
              For any questions, contact us at:{" "}
              <a href="#">support@seoagent.com</a>
            </p>
          </div>

          <div className="footer">
            © 2026 SEO Agent. All rights reserved.
          </div>

        </div>
      </div>
    </>
  );
}